### ISSUE TITLE
Add option : Remove Background Behind Logo

### ISSUE THREAD

**Issue by anhhuynh5** [gcoro/react-qrcode-logo#17]
Can your team add option to remove background behind logo ? I think it's necessary for many people like me. Thank your team very much.

![image](https://user-images.githubusercontent.com/86942776/130327661-8b8dc474-9488-4971-807e-0ed0e9a4682f.png)

**Comment by gcoro** [comment]
Hi, this has been added in PR #22 and is available from version 2.7.0

**Comment by mmelilli** [comment]
Setting this property to "true", the qrcode doesn't work anymore. Maybe you could add the possibility to decide the size of the removed part? I think it removes too much qrcode at the center

**Comment by gcoro** [comment]
@mmelilli hello, I addressed that in pr #37 ; 
starting from v2.9.0 of this library the prop `removeQrCodeBehindLogo` doesn't add any more padding(=removed part) to the original logo size, but instead such padding size can be set with `logoPadding`

**Comment by getflourish** [comment]
`removeQrCodeBehindLogo` has no effect. Is this intentional?

<img width="1316" alt="Image" src="https://github.com/user-attachments/assets/b2544058-81d7-4846-87e5-a8df1a18756f" />

**Comment by getflourish** [comment]
@gcoro Ah, sorry for the confusion. The white area around the logo is part of the logo image. 

What I would expect: The parts where the logo image overlaps the black squares would erase the black square completely. 

I understand that I can use padding to fiddle with it, but I was hoping that `removeQrCodeBehindLogo` boolean would figure it out automatically.

qrcode.react has such a setting and I thought this would be the same:
https://www.npmjs.com/package/qrcode.react

```imageSettings.excavate```
> Whether or not to "excavate" the modules around the embedded image. This means that any modules the embedded image overlaps will use the background color. Use this to ensure clean edges around your image. It is also useful when embedding images with transparency.

**Comment by gcoro** [comment]
@getflourish ok now i understand, thanks for the explanation. this library does not have this setting at the moment sorry
