### ISSUE TITLE
Html2canvas   not  save

### ISSUE THREAD

**Issue by lxt410725** [gcoro/react-qrcode-logo#2]
When I added the logo icon, html2canvas couldn't save the qr code

**Comment by lxt410725** [comment]
When I added the logo icon, html2canvas couldn't save the qr code

**Comment by lxt410725** [comment]
When I added the logo icon, html2canvas couldn't save the qr code

**Comment by gcoro** [comment]
Hi, can you give more details about the issue please? 
Is the qr code captured but the logo image doesn't show, or the qr code does not show at all? 
And does the qr get captured correctly if you do not specify a logo image?

**Comment by lxt410725** [comment]
Sorry, it is my problem. When I use the logo format of ico icon, the whole qr code cannot be displayed. When I change the logo format to PNG or JPG, it is ok

**Comment by gcoro** [comment]
I see, it's probably a support problem of htlm2canvas for certain types of images. Glad you solved :thumbsup:
