### ISSUE TITLE
When i pass logo inside Code it doesn't work

### ISSUE THREAD

**Issue by gerhr** [gcoro/react-qrcode-logo#27]
So the problem: is it OK when Logo overlays dots, and QR becomes unrecognizable for cameras?

**Comment by gcoro** [comment]
Hello, if QR becomes unrecognizable you could either:
- reduce size of logo
- reduce opacity of logo
- increase error correction level of the QR 

That's why it is a choice to not put any limitations on logo size, since more than one way of customization is possible.
