### ISSUE TITLE
Download the QR image

### ISSUE THREAD

**Issue by fathah** [gcoro/react-qrcode-logo#35]
Is there a way to download the generated QR code when clicked on download button

**Comment by Michael-AT-Corporation** [comment]
For example you can set the id prop to "myQRCode" and the use the following code to download the QR image when you click the download button.
` const qrCodeCanvas = document.getElementById("myQRCode") as HTMLCanvasElement;
        const link = document.createElement('a');
        link.href = qrCodeCanvas.toDataURL();
        link.download = 'qrcode.png';
        link.click();`

**Comment by fathah** [comment]
@Michael-AT-Corporation  Thanks man! This works
