### ISSUE TITLE
How do we download this QR once generated with a logo?

### ISSUE THREAD

**Issue by mustali17** [gcoro/react-qrcode-logo#40]

**Comment by Michael-AT-Corporation** [comment]
Maybe #35 can help you

**Comment by Michael-AT-Corporation** [comment]
I don't really get what your poblem is.
Is the QR-Code on your web-application rendered and the image is missing? Or can't the Qr-Code be rendered at all?
If the QR-Code is rendered with the image then the download should work.
Also a screenshot or some code would be helpful :)
