### ISSUE TITLE
do not work build next app

### ISSUE THREAD

**Issue by NikolyUrsegov** [gcoro/react-qrcode-logo#45]
<img width="1406" alt="Снимок экрана 2023-11-01 в 00 48 21" src="https://github.com/gcoro/react-qrcode-logo/assets/105654011/f6157fdf-7bc2-4dc4-a524-564000106da2">

**Comment by gcoro** [comment]
Hello, setting `allowSyntheticDefaultImports : true` in your project tsconfig.json will fix this error
