### ISSUE TITLE
[not an issue] download function for those interested

### ISSUE THREAD

**Issue by rares-lupascu** [gcoro/react-qrcode-logo#54]
1. ref from QRCode does not give u access to the canvas dom element (@gcoro i honestly thing u should export with forwardRef and assign it to the canvas ... for this case this would help a lot + we would take out this warning in this case ```Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference.```)
2. use the id attribute to position on the canvas
```
<QRCode
  enableCORS={true} // to prevent tainted errors especially when using logos
  id="VERY-UNIQUE-ID"
  value="https://google.com"
  size={280}
  logoImage={[SOME IMAGE URL]}
/>
```
3. use the download code below and attach it where u need it
```
const download = useCallback(() => {
    var canvas = document.getElementById("VERY-UNIQUE-ID") as HTMLCanvasElement;
    if (!canvas) {
      return;
    }
    var link = document.createElement("a");
    link.download = "qr.webp";
    link.href = canvas?.toDataURL("image/webp", 1.0).replace("image/webp", "image/octet-stream");;
    link.click();
  }, []);
```

**Comment by gcoro** [comment]
hi, thank you for the suggestions :) 
I decided not to export the canvas ref, but, since the last version 3.0.0, I fixed the findDOMNode warning and provided a function to download the image directly from the QRCode ref.
