### ISSUE TITLE
Feature Request: Support for Multiple Radius Values for each QR Code Eyes

### ISSUE THREAD

**Issue by HelloTalib** [gcoro/react-qrcode-logo#59]
First of all, thank you for maintaining the **react-qrcode-logo package.** It’s been a fantastic tool for generating customized QR codes.

I'd like to request a feature to allow different radius values for each eye of the QR code. like this...
![qrcode-feat](https://github.com/user-attachments/assets/f8ea3184-6c8e-41b1-869b-5649bb6487ac)
This would enable more customized and visually appealing designs.

**Comment by gcoro** [comment]
hello! you can already specify different radius for each eye :) 
see documentation [here](https://github.com/gcoro/react-qrcode-logo/blob/master/res/eyeRadius_doc.md) - last example should be what you want
