### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [gcoro/react-qrcode-logo#8]
Hi @gcoro : 

1) I tried the module on codesandbox, but it doesn't seem to start, you could take a look:
[codesandbox](https://codesandbox.io/s/react-example-b9zet)

2) It would be possible to generate the qr codes with the following graphic:

Link: [Site](https://www.qrcode-monkey.com/)

![](https://cdn5.vectorstock.com/i/1000x1000/18/69/blue-qr-code-scanning-icon-or-design-logo-vector-18861869.jpg)

![](https://www.logolynx.com/images/logolynx/8b/8bbd277ef5e053d84e86e5567a8cc673.png)

![](http://goqr.me/_Resources/Persistent/c51e9cb94c6c3e953542c764bb97a0e1cf033ca3/qrcode-logo-design-starbucks.png)

**Comment by gcoro** [comment]
Hello!

1. I gave it a look and I think it may be an issue specific to codesandbox, check  [this issue](https://github.com/codesandbox/codesandbox-client/issues/667). 

2. No, you can't generate those specific QR Codes, at the moment... Anyway to check what you can or cannot do, you can clone and start [this project](https://github.com/gcoro/QRCodeCustomizer), which contains a simple demo of this package.

**Comment by Angelk90** [comment]
@gcoro : 
1. So it means that you can't use your module on Codesanbox?

2. I've already tried, I've noticed sometimes even when qrStyle is dots type, my device can't read it.

Could it support the following required features in the future?

P.s.

There is a way to contact you privately I don't know twitter, facebook or email.

There are some interesting facts about tsx that I would like to ask you, if possible.

**Comment by gcoro** [comment]
1. Hm looks like i can ([my codesandbox example](https://codesandbox.io/embed/falling-smoke-y7qmy)). Maybe you need to enable CORS permission somewhere on your preferences? Sorry if I'm no more helpful than this, I don't know much about Codesandbox... 

2. The QR Code unreadability may happen unfortunately and can depend on alot of things, like if the amount of info you are trying to encode is very big, if the two color are too similar, if the logo is too big or too opaque, if error correction level is too low, event the quality of the camera you're using.. You may need to try some times until you get a readable combination. 

Sure, my email is giulia994@ymail.com :)
